require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-minitest
  - rubocop-rake
AllCops:
  DisabledByDefault: false
  NewCops: true
Style/Documentation:
  Enabled: false
Layout/DotPosition:
  EnforcedStyle: trailing
  Enabled: true