require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake
AllCops:
  DisabledByDefault: false
  NewCops: enable
Style/Documentation:
  Enabled: false
Layout/DotPosition:
  EnforcedStyle: trailing
  Enabled: true
Metrics/MethodLength:
  Exclude:
    - 'db/**/*.rb'